analyzer:
  errors:
    avoid_renaming_method_parameters: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true